### ISSUE TITLE
Docker Setup: for V4.2.0 a new config folder must be created.

### ISSUE THREAD

**Issue by Admiraldr** [PiBrewing/craftbeerpi4-documentation#10]
For first time creating a docker image for V4.2.0 after running earlier versions, it is (as in a normal setup) not possible to use the config in the existing config directory. 

Best practice: 

- create a backup. 
- Rename or delete the old config directory.
- Create a new config directory and do all following steps as decribed in the docker section
- run the clean image in docker
- restore the backup

I also before everything did the following steps from the main instructions above. But I'm not sure if this is required for the docker setup.
```
sudo apt-get install libatlas-base-dev
sudo apt-get install pipx
```

**Comment by avollkopf** [comment]
I have added that to the documentation
