### ISSUE TITLE
Add new plugin to plugin list

### ISSUE THREAD

**Issue by mstrinzha** [PiBrewing/craftbeerpi4-documentation#6]
Could you please add https://github.com/mstrinzha/cbpi4_FermenterHysteresisWithChillerDiff to plugin list.

**Comment by avollkopf** [comment]
I will add it in the next couple of days. It would be great, if you could add some more details to the README file as it is in this [example](https://github.com/PiBrewing/cbpi4-PIDBoil/blob/main/README.md)

**Comment by avollkopf** [comment]
done
